name       : pycups
version    : 1.9.73
release    : 1
source     :
    - https://pypi.python.org/packages/source/p/pycups/pycups-1.9.73.tar.bz2 : c381be011889ca6f728598578c89c8ac9f7ab1e95b614474df9f2fa831ae5335
license    : GPL-2.0
summary    : Python bindings for cups
description: |
    This is a set of Python bindings for the libcups library from the CUPS project.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
    - cups-devel
rundeps    :
    - python3
build      : |
    python2 setup.py build
    python3 setup.py build
install    : |
    python2 setup.py install --root=%installroot% --no-compile -O0
    python3 setup.py install --root=%installroot% --no-compile -O0
