name       : pycups
version    : 1.9.74
release    : 12
source     :
    - https://pypi.python.org/packages/source/p/pycups/pycups-1.9.74.tar.bz2 : 86090f259a7c5d0d5caa3407a0e57c9e134027620cbc8f90bf4e37c8b53ed7b9
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Python bindings for cups
description: |
    This is a set of Python bindings for the libcups library from the CUPS project.
builddeps  :
    - pkgconfig(python3)
    - cups-devel
build      : |
    %python3_setup
install    : |
    %python3_install
